travis:
  secure:
    BINSTAR_TOKEN: p7Si0G8DAl8iY4bSkTOIRQ/IIvMWLJXZOLqcBdOxJliqZfHuw/jLJJIVtAjmowEFOvsiyOjbN3/C24ETkMwWCS+fp62yidqw5MrHm/kAVM8ppoSN3u6+nEL3EJeuzBqVAMxDNd2E01Tzv942KlgWCW4vsEirBGzC9SD0hThdGKFbn9j65JwCxmpPN55FzaRYieUGXC2CMZAQb05qWrJ2XjUPA2pIwQq9M11tC3Gc0PhFIYBWsHZOktePC1ALgvJVx53TodT+hIw3kFFndHYWlyn9ouFeHjKuOgFgyZbj/Ym+3aXmgcdYRX/Snpsg2DIPAwPLqPxXLgWiIDJgC/2kEF7FaM+XDKM4pJwixJPKdddlBAYbjtJ5+eFmYZHw9hYazK+hlKPoQApte2/0LisCW3gTON1wdi5BFXJK4Y2rLiEE/HNWVHvdV6N+JkGX6rU6yS/rMZBfXV+k5UcEahPA8WHSD2HT9ulw+DRbMewsaFHCUtFEXDN8vJ0KaV04fNFbSD3ZxcrNJiRD77cKGlkqFaaAZgc5QKED3TpyEofGoZ/Tz66KwjBtvuuspWYcdR5L/eWIyrTTZg4UkNw9JwobTHuamhteMwlN/0lAmJXez3+xHnXSHEBGy87wbmZvEt88a0TzBaJy6Tt76QfJgGZbR/sEPiFfE5ZBPa08yTaHeD8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
